--------------------------------------------------------
--  파일이 생성됨 - 수요일-8월-05-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PRODUCTFIN1
--------------------------------------------------------

  CREATE TABLE "PRODUCTFIN" 
   (	"PRDNO" VARCHAR2(4), 
	"PRDNAME" VARCHAR2(50), 
	"PRDPRICE" NUMBER(8,0), 
	"PRDMAKER" VARCHAR2(30), 
	"PRDCOLOR" VARCHAR2(30), 
	"CTGNO" NUMBER(3,0)
   ) ;
Insert into PRODUCTFIN (PRDNO,PRDNAME,PRDPRICE,PRDMAKER,PRDCOLOR,CTGNO) values ('1','삼성 냉장고 비스포크',1620000,'삼성전자','새틴 코럴',1);
Insert into PRODUCTFIN (PRDNO,PRDNAME,PRDPRICE,PRDMAKER,PRDCOLOR,CTGNO) values ('2','LG 디오스 와인셀러',1367000,'LG전자','검정',1);
Insert into PRODUCTFIN (PRDNO,PRDNAME,PRDPRICE,PRDMAKER,PRDCOLOR,CTGNO) values ('3','QLED 8K TV',2175000,'삼성전자','블랙',1);
Insert into PRODUCTFIN (PRDNO,PRDNAME,PRDPRICE,PRDMAKER,PRDCOLOR,CTGNO) values ('4','올레드 TV 55',799000,'LG전자','검정',1);
Insert into PRODUCTFIN (PRDNO,PRDNAME,PRDPRICE,PRDMAKER,PRDCOLOR,CTGNO) values ('5','UHD 커브드 65인치',2250000,'삼성전자','은색',1);
Insert into PRODUCTFIN (PRDNO,PRDNAME,PRDPRICE,PRDMAKER,PRDCOLOR,CTGNO) values ('6','유아용 세발 자전거',76000,'삼천리 자전거','빨강',3);
Insert into PRODUCTFIN (PRDNO,PRDNAME,PRDPRICE,PRDMAKER,PRDCOLOR,CTGNO) values ('7','로드 사이클 자전거',150000,'알톤','검정',3);
Insert into PRODUCTFIN (PRDNO,PRDNAME,PRDPRICE,PRDMAKER,PRDCOLOR,CTGNO) values ('8','여성용 클래식 자전거',100000,'알톤','핑크',3);
Insert into PRODUCTFIN (PRDNO,PRDNAME,PRDPRICE,PRDMAKER,PRDCOLOR,CTGNO) values ('9','노트북9 metal',1390000,'도시바','은색',2);
Insert into PRODUCTFIN (PRDNO,PRDNAME,PRDPRICE,PRDMAKER,PRDCOLOR,CTGNO) values ('10','HP 게이밍 노트북',1200000,'HP','흰색',2);
Insert into PRODUCTFIN (PRDNO,PRDNAME,PRDPRICE,PRDMAKER,PRDCOLOR,CTGNO) values ('11','32인치 LED 모니터',299000,'LG전자','검정',2);
Insert into PRODUCTFIN (PRDNO,PRDNAME,PRDPRICE,PRDMAKER,PRDCOLOR,CTGNO) values ('12','광시야각 LED 모니터',195000,'삼성전자','흰색',2);
Insert into PRODUCTFIN (PRDNO,PRDNAME,PRDPRICE,PRDMAKER,PRDCOLOR,CTGNO) values ('13','등산배낭 옵티마',68000,'밀레','자주',4);
Insert into PRODUCTFIN (PRDNO,PRDNAME,PRDPRICE,PRDMAKER,PRDCOLOR,CTGNO) values ('14','35L 등산배낭',49000,'(주)셀파','노랑',4);
Insert into PRODUCTFIN (PRDNO,PRDNAME,PRDPRICE,PRDMAKER,PRDCOLOR,CTGNO) values ('15','원터치 자동 텐트',58000,'이지트래블러','그린',4);
Insert into PRODUCTFIN (PRDNO,PRDNAME,PRDPRICE,PRDMAKER,PRDCOLOR,CTGNO) values ('16','그늘막 텐트',33000,'밀레','그린',4);
